### PR TITLE
Reimplement Indicator.mqh  with  double linked list

### PR DESCRIPTION
**Pull request by janckerchen**
The ideas:

1.  class IndicatorBuffer is an abstract for  data buffer implemented by double linked list.  Implementation with Dynamic array (with ArrayResize)  has performance issue.  EA slow down rapidly as data grows because ArraySetAsSeries +ArrayResize will move data in memory.

2. IndicatorBuffer always keep the list sorted according to bar time,  the newer value insert to head.  so there is a head pointer.

3. when IndicatorBuffer grows to max_size, the limit of buffer capcity, IndicatorBuffer discard oldest value,  so there is a tail pointer and double linked node.

4. class Indicator is an abstract for multi-buffer indicator.  It has a array of IndicatorBuffer  and the length  of array is determined by parameter to constructor.

5. Indicator.mq4 is a demo to demonstrate how to use the base class to implement a customize indicator,  and show the value on MT4 chart.

Refs: #23, #24

### CODE REVIEW

**Comment by kenorb** [comment]
@janckerchen Thanks, I'll test it soon. If you'd like, I can recreate a job, so you can get a bounty. If so, send me your mql username.

**Comment by kenorb** [comment]
@janckerchen Thanks, I'll test it soon. If you'd like, I can recreate a job, so you can get a bounty. If so, send me your mql username.

**Comment by janckerchen** [comment]
@kenorb you are welcome, I get a lot from your awesome work, it's a chance to me to give back.

I found a  bug in GetInt() and push a new commit.

**Comment by janckerchen** [comment]
@kenorb  don't merge this pull request, there are bugs in linked list implements especially as mt4 terminal reconnect to server for some reason. I found it not easy  to develop double linked list in handy way, so I switch to [a professional LinkedList implement](https://github.com/dingmaotu/mql4-lib/blob/master/Collection/LinkedList.mqh). It's pure mql4 with iterator,  efficient and easy to use.

**Comment by kenorb** [comment]
Ok, I'll be testing it in a week or few. I've seen you've removed ENUM_S_INDICATOR enum, this will be needed by the strategies, so I'll have to figure out which place would be the best to place it.

**Pull request merged**
